[[repos]]
repo = "builtin"
hooks = [
  {id = "check-merge-conflict"},
  {id = "check-toml"},
  {id = "check-yaml"},
  {id = "end-of-file-fixer"},
  {id = "trailing-whitespace"}
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.0"
hooks = [
  {id = "ruff-check", args = ["--fix", "--show-fixes"]},
  {id = "ruff-format"}
]
